"""Builds a grounded prompt for legal answer generation.

The LLM is responsible only for generating the direct answer.
Source metadata, legal excerpts, pages, sections, and citation markers
are controlled by the application and are not generated by the LLM.
"""

from __future__ import annotations

from legal_rag.query.models import Citation, RerankedChunk


_SYSTEM_AR = (
    "أنت مساعد قانوني يعمل باللغة العربية. "
    "أجب عن سؤال المستخدم مباشرة وباختصار. "

    "اعتمد حصريًا على المقاطع المرجعية المرفقة أدناه، "
    "ولا تستخدم أي معرفة من خارجها. "

    "مهمتك هي كتابة الإجابة فقط. "
    "لا تكتب قسمًا بعنوان النص القانوني أو المصدر أو الصفحة. "
    "لا تعيد كتابة بيانات المصدر. "

    "لا تكتب أرقام المصادر مثل [1] أو [2] في إجابتك. "
    "سيضيف النظام أرقام المصادر تلقائيًا بعد التحقق من الأدلة. "

    "إذا كان السؤال عن حالة محددة أو مبلغ محدد، "
    "طبّق القاعدة الموجودة في المصادر على الحالة المذكورة فقط. "

    "حافظ على جميع الأرقام والمبالغ والعملات والتواريخ "
    "كما وردت في المصادر. "
    "لا تغيّر أي رقم. "
    "لا تخترع مادة قانونية أو مصدرًا أو صفحة. "

    "لا تضف معلومات جانبية أو ملخصًا عامًا للمصادر. "
    "لا تضف استنتاجًا غير مدعوم بالمقاطع. "

    "إذا كانت المقاطع غير كافية للإجابة، "
    "اذكر بوضوح أن المعلومات المتاحة غير كافية بدلًا من التخمين. "

    "اكتب إجابة قصيرة ومباشرة."
)


_SYSTEM_EN = (
    "You are a legal assistant. "
    "Answer the user's question directly and concisely. "

    "Use only the provided numbered source excerpts and no outside knowledge. "

    "Your task is to write the answer only. "
    "Do not create sections for legal text, source, page, or metadata. "
    "Do not reproduce source metadata. "

    "Do not write citation markers such as [1] or [2]. "
    "The system will add citation markers automatically. "

    "If the question contains a specific case or amount, "
    "apply the legal rule from the evidence only to that case. "

    "Preserve all numbers, amounts, currencies, and dates exactly "
    "as they appear in the sources. "
    "Do not change any number. "
    "Do not invent legal articles, sources, or pages. "

    "Do not add unrelated information or unsupported conclusions. "

    "If the evidence is insufficient, explicitly say so instead of guessing. "

    "Keep the answer short and direct."
)


_SYSTEM_MIXED = _SYSTEM_EN + (
    " Respond in the same language as the user's question."
)


def _system_prompt(language: str) -> str:
    return {
        "ar": _SYSTEM_AR,
        "en": _SYSTEM_EN,
    }.get(language, _SYSTEM_MIXED)


def build_grounded_prompt(
    query: str,
    chunks: list[RerankedChunk],
    language: str = "mixed",
) -> tuple[str, list[Citation]]:
    """Build the grounded answer prompt and citation metadata."""

    citations: list[Citation] = []
    evidence_blocks: list[str] = []

    for i, chunk in enumerate(chunks, start=1):
        marker = f"[{i}]"

        citations.append(
            Citation(
                marker=marker,
                chunk_id=chunk.chunk_id,
                document_id=chunk.document_id,
                source_file=chunk.source_file,
                section_title=chunk.section_title,
                page=chunk.page,
            )
        )

        locator_parts: list[str] = []

        if chunk.section_title:
            locator_parts.append(
                f"section: {chunk.section_title}"
            )

        if chunk.page is not None:
            locator_parts.append(
                f"page: {chunk.page}"
            )

        locator = ", ".join(locator_parts)

        header = (
            f"{marker} Source: "
            f"{chunk.source_file or chunk.document_id}"
        )

        if locator:
            header += f" ({locator})"

        evidence_blocks.append(
            f"{header}\n"
            f"{chunk.text.strip()}"
        )

    evidence_text = (
        "\n\n".join(evidence_blocks)
        if evidence_blocks
        else "(no relevant excerpts found)"
    )

    prompt = (
        f"{_system_prompt(language)}\n\n"

        "### سؤال المستخدم\n"
        f"{query.strip()}\n\n"

        "### المقاطع المرجعية\n"
        f"{evidence_text}\n\n"

        "### تعليمات الإجابة\n"
        "اكتب الإجابة المباشرة فقط. "
        "لا تكتب أرقام المصادر مثل [1] أو [2]. "
        "لا تكتب Legal Text أو Sources أو Page أو Section. "
        "سيضيف النظام بيانات المصادر تلقائيًا.\n\n"

        "### الإجابة\n"
    )

    return prompt, citations